/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.catcher92.demo.mapper;

import com.catcher92.demo.framework.mapper.BaseMapper;
import com.catcher92.demo.po.UserDeptRoleLink;
import com.catcher92.demo.po.UserDeptRoleLinkExample;

public interface UserDeptRoleLinkMapper extends com.catcher92.demo.framework.mapper.BaseMapper<com.catcher92.demo.po.UserDeptRoleLink, com.catcher92.demo.po.UserDeptRoleLinkExample> {
}