/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.catcher92.demo.mapper;

import com.catcher92.demo.framework.mapper.BaseMapper;
import com.catcher92.demo.po.DepartmentPo;
import com.catcher92.demo.po.DepartmentPoExample;

public interface DepartmentPoMapper extends com.catcher92.demo.framework.mapper.BaseMapper<com.catcher92.demo.po.DepartmentPo, com.catcher92.demo.po.DepartmentPoExample> {
}