/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.catcher92.demo.mapper;

import com.catcher92.demo.framework.mapper.BaseMapper;
import com.catcher92.demo.po.DeptPo;
import com.catcher92.demo.po.DeptPoExample;

public interface DeptPoMapper extends com.catcher92.demo.framework.mapper.BaseMapper<com.catcher92.demo.po.DeptPo, com.catcher92.demo.po.DeptPoExample> {
}