/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.catcher92.demo.mapper;

import com.catcher92.demo.framework.mapper.BaseMapper;
import com.catcher92.demo.po.ResourcePo;
import com.catcher92.demo.po.ResourcePoExample;

public interface ResourcePoMapper extends com.catcher92.demo.framework.mapper.BaseMapper<com.catcher92.demo.po.ResourcePo, com.catcher92.demo.po.ResourcePoExample> {
}