/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.catcher92.demo.mapper;

import com.catcher92.demo.framework.mapper.BaseMapper;
import com.catcher92.demo.po.RoleResourceLink;
import com.catcher92.demo.po.RoleResourceLinkExample;

public interface RoleResourceLinkMapper extends com.catcher92.demo.framework.mapper.BaseMapper<com.catcher92.demo.po.RoleResourceLink, com.catcher92.demo.po.RoleResourceLinkExample> {
}