/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.catcher92.demo.mapper;

import com.catcher92.demo.framework.mapper.BaseMapper;
import com.catcher92.demo.po.RolePo;
import com.catcher92.demo.po.RolePoExample;

public interface RolePoMapper extends com.catcher92.demo.framework.mapper.BaseMapper<com.catcher92.demo.po.RolePo, com.catcher92.demo.po.RolePoExample> {
}