/**
 * This file is automatically generated by MyBatis Generator, do not modify.
 */
package com.catcher92.demo.mapper;

import com.catcher92.demo.framework.mapper.BaseMapper;
import com.catcher92.demo.po.UserPo;
import com.catcher92.demo.po.UserPoExample;

public interface UserPoMapper extends com.catcher92.demo.framework.mapper.BaseMapper<com.catcher92.demo.po.UserPo, com.catcher92.demo.po.UserPoExample> {
}